# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18bd6966ddc0afbae98ece8a69e6d34611f6b6c2fe6eba6e02392fda39ba8eafa356a8a3e6ec1edef4fb19817c243deb583ae81e684c818a7060e053fd129b15

test:
  secret_key_base: 47007a75969a46f569060352d04d6c995d9d31d31ff68fb8d8ff69e8c91cec6e735ec06709888a11d43384db95a6df611e6bb003dff6255c60971e255f8c6d54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
